### ISSUE TITLE
next.js报错

### ISSUE THREAD

**Issue by linzeguang** [foca-js/foca#10]
error - Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/Users/linzeguang/Desktop/yyz/my-app/node_modules/foca/es/model/defineModel' imported from /Users/linzeguang/Desktop/yyz/my-app/node_modules/foca/es/index.js
Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/Users/linzeguang/Desktop/yyz/my-app/node_modules/foca/es/model/defineModel' imported from /Users/linzeguang/Desktop/yyz/my-app/node_modules/foca/es/index.js
    at new NodeError (internal/errors.js:322:7)
    at finalizeResolution (internal/modules/esm/resolve.js:318:11)
    at moduleResolve (internal/modules/esm/resolve.js:776:10)
    at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:887:11)
    at Loader.resolve (internal/modules/esm/loader.js:89:40)
    at Loader.getModuleJob (internal/modules/esm/loader.js:242:28)
    at ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:76:40)
    at link (internal/modules/esm/module_job.js:75:36) {
  code: 'ERR_MODULE_NOT_FOUND',
  page: '/'
}

**Comment by geekact** [comment]
你应该是开启了es module，import时后缀必须指定。切换到commonJS方案可解决问题，或者在执行node时加上`--experimental-specifier-resolution=node`也可解决问题。

我这边也看下如何解决在框架层面解决

**Comment by geekact** [comment]
https://nodejs.org/dist/latest-v16.x/docs/api/all.html#all_esm_customizing-esm-specifier-resolution-algorithm

**Comment by geekact** [comment]
升级到 foca@0.10.1 即可修复报错。之前都是在vite/webpack环境下使用，所以没有遇到node的问题

**Comment by linzeguang** [comment]
> 升级到foca@0.10.2就可以报修复错误。之前都是在vite/webpack环境下使用，所以没有遇到node的问题

升级到0.10.2解决了这个问题，但是新遇到了个问题就是next.js在node环境下运行没有localStorage和sessionStorage对象

**Comment by linzeguang** [comment]
TypeError: Cannot destructure property 'store' of 'useReduxContext(...)' as it is null.
    at useSelector (/Users/linzeguang/Desktop/yyz/my-app/node_modules/react-redux/lib/hooks/useSelector.js:50:7)
    at useModel (file:///Users/linzeguang/Desktop/yyz/my-app/node_modules/foca/dist/index.mjs:756:10)
    at Home (webpack-internal:///./src/pages/index.tsx:21:63)
    at renderWithHooks (/Users/linzeguang/Desktop/yyz/my-app/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5448:16)
    at renderIndeterminateComponent (/Users/linzeguang/Desktop/yyz/my-app/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5521:15)
    at renderElement (/Users/linzeguang/Desktop/yyz/my-app/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5736:7)
    at renderNodeDestructive (/Users/linzeguang/Desktop/yyz/my-app/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5875:11)
    at renderNode (/Users/linzeguang/Desktop/yyz/my-app/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6009:12)
    at renderChildrenArray (/Users/linzeguang/Desktop/yyz/my-app/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5965:7)
    at renderNodeDestructive (/Users/linzeguang/Desktop/yyz/my-app/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5897:7)
wait  - compiling /_error (client and server)...
wait  - compiling...
event - compiled client and server successfully in 97 ms (210 modules)
error - TypeError: Cannot destructure property 'store' of 'useReduxContext(...)' as it is null.

还有遇到这个报错，在使用useModel的时候

<img width="385" alt="image" src="https://user-images.githubusercontent.com/41186195/164358982-be3ea62e-f931-4c99-aa38-8d712e067a67.png">

**Comment by geekact** [comment]
你是要使用persist吗？这个应该是个无解的问题，redux-persist之前也讨论过这个，https://github.com/rt2zz/redux-persist/issues/1008 。

目前只能判断是否ssr，然后换成 memoryStorage 。之前有想过使用cookie来实现，但是不确定是否为业界标准方案

**Comment by geekact** [comment]
> TypeError: Cannot destructure property 'store' of 'useReduxContext(...)' as it is null.

是否在入口加上了 `FocaProvider`标签？

**Comment by linzeguang** [comment]
> 

忘记添加了不好意思，文档里没体现就疏忽了，您这边看文档要不要补充一下。

**Comment by linzeguang** [comment]
> > TypeError: Cannot destructure property 'store' of 'useReduxContext(...)' as it is null.
> 
> 是否在入口加上了 `FocaProvider`标签？

忘记添加了不好意思，文档里没体现就疏忽了，您这边看文档要不要补充一下。

**Comment by geekact** [comment]
https://foca.js.org/#/store?id=%e5%85%a5%e5%8f%a3
文档都有的

**Comment by geekact** [comment]
SSR的持久化这块可以讲讲你的需求，我收集一下，这样做出来的功能也更符合用户习惯。

**Comment by linzeguang** [comment]
> https://foca.js.org/#/store?id=%e5%85%a5%e5%8f%a3 文档都有的

哦哦看到了，不好意思哈，感谢

**Comment by geekact** [comment]
好的，希望这个库能让你准时下班，我这几天把nextjs的demo也放上去

**Comment by geekact** [comment]
经过一段时间研究，发现foca暂时无法用在nextjs中。原因是store是单一的，而node进程是内存常驻的，这意味着store会被所有请求共享。我将在文档中体现这个问题。感谢体验以及非常抱歉
